# NUMPY

In [1]:
import numpy as hey

#### Creating ARRAY

In [2]:
arr = hey.array([10,30,40])
print(arr)

[10 30 40]


In [3]:
arr1 = hey.array([[10,20,30],[20,30,40]])
print(arr1)

[[10 20 30]
 [20 30 40]]


In [4]:
arr3 = hey.array([[[10,20,30],[20,30,40]]])
print(arr3)

[[[10 20 30]
  [20 30 40]]]


#### Array attributes

In [5]:
print(arr3.dtype) #returns the data type 
print(arr3.ndim)   # returns the dimension of array
print(arr1.shape)   # returns (rows , columns)
print(arr.size)     # returns tOtal elements
print(arr1.size)
print(arr3.size)

int64
3
(2, 3)
3
6
6


In [6]:
hey.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
hey.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
hey.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
hey.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
hey.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
hey.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])

arr = hey.concatenate([arr1,arr2] ,axis=1)
print(arr)

[[30 40  1  2]
 [50 60  5  6]]


In [13]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
arr3 = arr1 + arr2
print(arr3)

[[31 42]
 [55 66]]


In [14]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
arr3 = arr1 - arr2
print(arr3)

[[29 38]
 [45 54]]


In [15]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
arr3 = arr1 * arr2
print(arr3)

[[ 30  80]
 [250 360]]


In [16]:
arr =hey.array([1,5,3,4,9,6,8,6])
hey.mean(arr)

np.float64(5.25)

In [17]:
hey.median(arr)

np.float64(5.5)

In [18]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
print(hey.concatenate([arr1,arr2]))

[[30 40]
 [50 60]
 [ 1  2]
 [ 5  6]]


In [19]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
print(hey.concatenate([arr1,arr2],axis=1))

[[30 40  1  2]
 [50 60  5  6]]


In [20]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
print(hey.hstack([arr1,arr2]))           #horizontal concatenation

[[30 40  1  2]
 [50 60  5  6]]


In [21]:
arr1 = hey.array([[30,40],[50,60]])
arr2 = hey.array([[1,2],[5,6]])
print(hey.vstack([arr1,arr2]))            #Vertical concatenation

[[30 40]
 [50 60]
 [ 1  2]
 [ 5  6]]


In [25]:
## Splitting values
arr =hey.array([1,5,3,4,9,6,8,6])
print(hey.array_split(arr,4))

[array([1, 5]), array([3, 4]), array([9, 6]), array([8, 6])]


In [27]:
## Adding and Removing in Array

In [28]:
arr =hey.array([1,5,3,4,9,6,8,6])
hey.append(arr ,56)

array([ 1,  5,  3,  4,  9,  6,  8,  6, 56])

In [29]:
arr ## DOES not nodify array

array([1, 5, 3, 4, 9, 6, 8, 6])

In [33]:
hey.insert(arr,1,10)
#does not modify also

array([ 1, 10,  5,  3,  4,  9,  6,  8,  6])

In [34]:
print(arr)

[1 5 3 4 9 6 8 6]


In [35]:
hey.delete(arr,[2])

array([1, 5, 4, 9, 6, 8, 6])

In [36]:
print(arr)

[1 5 3 4 9 6 8 6]


In [37]:
arr1 = hey.array([[30,40],[50,60]])
hey.insert(arr1,2 ,[80,90])

array([30, 40, 80, 90, 50, 60])

In [39]:
arr1 = hey.array([[30,40],[50,60]])
hey.insert(arr1,1 ,[80,90],axis=1)

array([[30, 80, 40],
       [50, 90, 60]])

In [41]:
hey.delete(arr1,[2])

array([30, 40, 60])

In [43]:
Fall=hey.array([2,9,6,4,10,33,17])
print(hey.sort(Fall))

[ 2  4  6  9 10 17 33]


In [45]:
Fall=hey.array([[2,9,6,4],[10,33,17,15]])
print(hey.sort(Fall))

[[ 2  4  6  9]
 [10 15 17 33]]


In [49]:
#Search values
fall=hey.array([2,9,6,4,10,33,16])
s=hey.where(fall == 10)
print(s)

(array([4]),)


In [50]:
d = hey.where(fall % 2 == 0)
print(d)

(array([0, 2, 3, 4, 6]),)


In [54]:
old = hey.array([20,40,60,30,80])

fa = [True ,False ,True,False,True]
new =old[fa]
print(new)

[20 60 80]


In [61]:
a = hey.array([20,50,60,90,40,60])
print(hey.sum(a))
print(hey.min(a))
print(hey.max(a))
print(hey.size(a))
print(hey.std(a))
print(hey.var(a))

320
20
90
6
21.343747458109497
455.5555555555556
